name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    #- name: Build with Gradle
    #  run: ./gradlew build

    #1
    - name: Decode Keystore
      env:
         ENCODED_STRING: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}
         SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}

      run: |
         echo $ENCODED_STRING | wc
         echo "SGVsbG8gV29ybGQK" | base64 -d
         echo "Dave was here"
         echo $SIGNING_KEY_STORE_PATH | wc
         echo $ENCODED_STRING | base64 -d > $SIGNING_KEY_STORE_PATH
         ls -l $SIGNING_KEY_STORE_PATH
    #2
    - name: Build Release apk
      env:
         SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}
         SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
         SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
         SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      run: ./gradlew assembleRelease

    #3
    - name: Upload Release Build to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: release-artifacts
        path: app/build/outputs/apk/release/
